import{g as f,a as C,b as E,c as S}from"./assets/main-BsnXccMc.js";const u=document.getElementById("scrollTopButton");window.onscroll=function(){document.body.scrollTop>300||document.documentElement.scrollTop>300?u.classList.add("active"):u.classList.remove("active")};u.onclick=function(){window.scrollTo({top:0,behavior:"smooth"})};const v=f();function k(e){return`
    <li id="${e.id}" class="listener" onclick="openModal('${e.id}')">
        <div class="game-category-card">
            <div class="overlay-div">
                <img class="gameByCategory-img" src="${e.image}" alt="${e.title}">
                <p class="overlay-txt">quick view</p>
            </div>
            <div class="game-category-details">
                <h3 class="game-category-title">${e.title}</h3>
                <p class="game-category-author">${e.author}</p>
            </div>
        </div>
    </li>
    `}function T(e,t){const o=document.querySelector(`.game-category[data-category="${e}"]`);if(o){const a=o.querySelector(".mask"),n=t.map(s=>k(s)).join(""),i=o.querySelector(".games-category-list");i.innerHTML=n,a.style.display="none"}}const p=C(v);function q(){Object.keys(p).forEach(e=>{const t=p[e];T(e,t)})}function A(e){const t=document.createElement("div");t.className="game-category",t.setAttribute("data-category",e);const o=document.createElement("div");o.className="category-title";const a=document.createElement("div");a.className="mask",a.innerHTML='<div class="loader"></div>';const n=document.createElement("span");n.textContent=e.toUpperCase(),o.appendChild(n);const i=document.createElement("div");i.className="games";const s=document.createElement("ul");s.className="games-category-list",i.appendChild(s);const c=document.createElement("button");return c.id=e.replace(/\s+/g,"_"),c.classList.add("see-more"),c.textContent="SEE MORE",c.addEventListener("click",M),t.appendChild(o),t.appendChild(a),t.appendChild(i),t.appendChild(c),t}function M(){window.scrollTo({top:0,behavior:"smooth"})}function b(){const e=document.querySelector(".top-games-list");v.forEach(t=>{const o=A(t);e.appendChild(o)})}//! Виклик функції при завантаженні сторінки
document.addEventListener("DOMContentLoaded",()=>{b(),q()});document.addEventListener("DOMContentLoaded",()=>{const e=document.querySelectorAll(".category-item"),t=document.querySelector(".topGamesTitle"),o=Array.from(e).find(s=>s.textContent.trim()==="All Categories"),a=document.querySelector(".top-games-list");function n(){t.textContent.trim()==="Most Popular Games"&&(e.forEach(s=>s.classList.remove("active-category")),o.classList.add("active-category"),a.classList.remove("category-active"))}function i(){t.innerHTML="Most Popular Games",a.classList.remove("category-active"),n()}o.addEventListener("click",i),e.forEach(s=>{s.addEventListener("click",()=>{const c=s.textContent.trim().toUpperCase();if(c==="ALL CATEGORIES")i();else if(t.innerHTML=`${c} Games`,e.forEach(r=>r.classList.remove("active-category")),s.classList.add("active-category"),document.querySelectorAll(".game-category").forEach(r=>{r.style.display=r.getAttribute("data-category").toUpperCase()===c?"block":"none"}),a.classList.add("category-active"),window.innerWidth<=768){const r=document.getElementsByTagName("aside")[0];r.style.display="none"}})}),document.querySelectorAll(".see-more").forEach(s=>{s.addEventListener("click",()=>{const c=s.id.replace("see-more-","").replace("_"," "),r=E(c);t.innerHTML=`${c} Games`,document.querySelectorAll(".game-category").forEach(m=>{m.style.display="none"}),a.innerHTML="",r.forEach(m=>{const L=w(m);a.appendChild(L)}),a.classList.add("category-active")})}),n()});function w(e){const t=document.createElement("li");return t.id=e.id,t.className="listener",t.setAttribute("onclick",`openModal('${e.id}')`),t.innerHTML=`
        <div class="game-category-card">
            <div class="overlay-div">
                <img class="gameByCategory-img" src="${e.image}" alt="${e.title}">
                <p class="overlay-txt">quick view</p>
            </div>
            <div class="game-category-details">
                <h3 class="game-category-title">${e.title}</h3>
                <p class="game-category-author">${e.author}</p>
            </div>
        </div>
    `,t}window.openModal=B;const l=document.querySelector(".modal"),y=l.querySelector(".modal-body"),G=l.querySelector(".modal-close"),d=l.querySelector(".add-to-list"),x=l.querySelector(".under-btn-text");async function B(e){try{const t=await S(e);l.setAttribute("data-game",JSON.stringify(t)),$(t),l.classList.add("open"),document.body.style.overflow="hidden",h(N(t))}catch(t){console.log("Error loading game details",t)}}function $(e){const t=document.querySelector(".game-cover"),o=document.querySelector(".game-title"),a=document.querySelector(".game-author"),n=document.querySelector(".game-description"),i=document.querySelector(".marketplace-logo.steam"),s=document.querySelector(".marketplace-logo.trailer");t.src=e.image,t.alt=e.title,o.textContent=e.title,a.textContent=`by ${e.author}`,n.textContent=e.description||"No description available",i.href=e.links.steam||"#",s.href=e.links.Trailer||"#"}function N(e){return(JSON.parse(localStorage.getItem("shoppingList"))||[]).some(o=>o.id===e.id)}function h(e){const t=e?"Remove from shopping list":"Add to shopping list";d.textContent=t,x.textContent=e?"Removed from shopping list":"Added to shopping list",d.classList.add("show-text"),setTimeout(()=>{d.classList.remove("show-text")},4e3)}function D(e){e.stopPropagation();let t=JSON.parse(localStorage.getItem("shoppingList"))||[];const o=JSON.parse(l.getAttribute("data-game")),a=t.some(n=>n.id===o.id);a?t=t.filter(n=>n.id!==o.id):(t.push(o),console.log(t)),localStorage.setItem("shoppingList",JSON.stringify(t)),h(!a)}d.addEventListener("click",D);function g(){l.classList.remove("open"),document.body.style.overflow=""}G.addEventListener("click",g);y.addEventListener("click",function(e){e.target===y&&g()});document.addEventListener("keydown",function(e){e.key==="Escape"&&g()});
//# sourceMappingURL=index.js.map
